# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 23:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('building', models.CharField(choices=[('apto', 'Apartamento'), ('house', 'Casa'), ('pens', 'Pensionato'), ('hostel', 'Hostel'), ('rep', 'Rep\xfablica')], default='apto', max_length=8)),
                ('type', models.CharField(choices=[('one', 'Individual'), ('many', 'Coletivo'), ('couple', 'Casal')], default='one', max_length=8)),
                ('bathroom', models.CharField(choices=[('priv', 'Individual/Privativo'), ('col', 'Coletivo'), ('split', 'Compartilhado para Dois')], default='priv', max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Somente Homens'), ('F', 'Somente Mulheres'), ('ND', 'Homens/Mulheres')], default='ND', max_length=3)),
                ('description', models.TextField(default='N\xe3o informado', max_length=200)),
                ('smoking', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('include_bills', models.BooleanField(default=False)),
                ('visits', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('furniture', models.BooleanField(default=False)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)])),
                ('active', models.BooleanField(default=True)),
                ('region', models.CharField(default='N\xe3o Informado', max_length=20)),
                ('cep', models.CharField(default='N\xe3o Informado', max_length=12)),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.State')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
